app/Enums/UserRoleEnum.php
app/Http/Controllers/HomeController.php
app/Http/Controllers/Settings/ProfileController.php
routes/api.php

overview
minor config route user dan router api
cc @jabardigitalservice/jds-backend @rachadiannovansyah

minor config route basic

---

app/Http/Requests/EditAssetRequest.php
app/Http/Requests/UpdateReservationRequest.php

review, komplitin form request edit aja :)
@rindibudiaramdhan @ayocodingit

completed rules of validated

---

app/Http/Controllers/V1/AssetController.php
app/Http/Requests/StoreAssetRequest.php
app/Models/Asset.php
resources/lang/vendor/enum/en/validation.php

miss logic on filter status
review intern @rindibudiaramdhan @ayocodingit

fixing logic on filter

---

composer.json
phpcs.xml

overview 
implementasi psr 12
cc : @jabardigitalservice/jds-backend @yohang88 @rachadiannovansyah @rindibudiaramdhan

implementasi psr 12

---

app/Http/Controllers/Settings/ProfileController.php
app/Http/Controllers/V1/DashboardController.php
app/Http/Controllers/V1/ReservationController.php
app/Http/Controllers/V1/ReservedController.php
app/Http/Requests/AcceptReservationRequest.php
app/Models/Reservation.php
app/Providers/AuthServiceProvider.php
app/User.php
packages/robsontenorio/laravel-keycloak-guard/src/KeycloakGuard.php

Mereplace cara get user logged in from keycloak 
@rindibudiaramdhan 
@ayocodingit

remove getUser replace to Auth::user() from key cloak

---

app/Http/Requests/EditAssetRequest.php
app/Http/Requests/StoreAssetRequest.php
database/migrations/2021_01_10_004844_create_assets_table.php

**Overview**
make description field nullable (not required)
cc kang @rindibudiaramdhan @ayocodingit @yohang88 @sandisunandar99 @aldidoanta @firmanhxc

make description field not required (nullable)

---

app/Http/Controllers/V1/ReservationController.php
config/keycloak.php
phpcs.xml
resources/lang/en/validation.php
resources/lang/id/validation.php

[overview]
- Bisa edit reservasi maksimal kurang dari 30 menit sebelum acara dimulai
kasus : 
Misalnya saya udah booking jam 19.00, dan sekarang jam 18.36. Harusnya saya udah nggak boleh edit lagi reservasinya. Karena edit reservasi harus dilakukan paling lambat jam 18.30.
cc @jabardigitalservice/jds-backend @rachadiannovansyah @rindibudiaramdhan

add  validasi revervation update

---

app/Http/Requests/StoreAssetRequest.php
app/Models/Asset.php
database/migrations/2021_02_02_045318_add_field_capacity_on_asset_table.php

Overview :
- Tambah migrasi baru bernama 'capacity' pada tabel asset
- Penyesuaiin field capacity pada form tambah (endpoint store)
Cc: kang @ayocodingit @rindibudiaramdhan  @jabardigitalservice/jds-backend

add new field capacity on asset table

---

app/Mail/ReservationApprovalMail.php
app/Mail/ReservationStoreMail.php
composer.json
config/cache.php
config/database.php
config/filesystems.php
config/session.php
phpcs.xml
public/index.php
resources/lang/id/auth.php
resources/lang/id/pagination.php
tests/CreatesApplication.php
tests/SeedDatabase.php
tests/SeedDatabaseState.php
tests/TestCase.php

overview
add composer phpcs dan phpcbf
cc: @jabardigitalservice/jds-backend @rindibudiaramdhan @rachadiannovansyah

add composer phpcs dan phpcbf

---

app/Rules/AssetReservationRule.php

overview
already approved 
cc: @jabardigitalservice/jds-backend @rachadiannovansyah

fix alreadyApproved

---

.github/workflows/ci.yml
app/Http/Controllers/V1/ReservedController.php
database/factories/AssetFactory.php
database/migrations/2021_01_14_120758_add_user_fullname_at_reservations_table.php
database/migrations/2021_01_22_123800_add_column_email_to_reservations_table.php
database/migrations/2021_02_02_045318_add_field_capacity_on_asset_table.php
phpunit.xml

seeder update

---

app/Mail/ReservationApprovalMail.php
app/Models/Reservation.php
resources/views/emails/reservationStore.blade.php

Bug Fix Email Notification yang diterima baik oleh Admin ataupun oleh Pegawai.
Bug Fix Notifikasi Emailnya yaitu:
- Notifikasi Email ketika ada reservasi baru:
- belum ada nama pegawai yang mengajukan reservasi
- Notifikasi Email ketika reservasi diapprove atau ditolak oleh admin:
- catatan approval tidak tampil
- status approval masih ditolak semua walaupun ketika approval statunya disetujui.
@jabardigitalservice/jds-backend @rachadiannovansyah @ayocodingit

Bug Fix Email Notification

---

app/Http/Controllers/V1/ReservationController.php
app/Http/Requests/ReservationRequest.php
app/Models/Reservation.php
app/Policies/ReservationPolicy.php
app/Providers/AuthServiceProvider.php
app/Rules/AssetReservationRule.php
app/User.php
packages/robsontenorio/laravel-keycloak-guard/src/KeycloakGuard.php
phpcs.xml

[OVERVIEW]
Add authorization on reservation
- Create ReservationPolicy
- Add hasRole and hasPermission
- Add approval_status Enums Reservation 
@jabardigitalservice/jds-backend @yohang88 @rachadiannovansyah

Add authorization on reservation

---

app/Http/Controllers/V1/ReservationController.php
app/Models/Reservation.php
config/mail.php
phpunit.xml
tests/Feature/AssetTest.php
tests/Feature/ReservationTest.php
tests/Feature/ReservedTest.php

Overview :
- Up coverage
- Fixing failure test
- Setup phpunit.xml
Note:
- Beberapa fungsi mungkin blm kena hit phpunit karna butuh riset lagi
- Current Coverage 79.83%

Update phpunit development

---

app/Http/Controllers/V1/ReservationController.php
app/Rules/AssetReservationRule.php

add pagination all reservation
approved 
cc @jabardigitalservice/jds-backend

add pagination all reservation

---

app/Enums/ResourceTypeEnum.php
app/Http/Controllers/V1/ReservationController.php
app/Http/Controllers/V1/ZoomController.php
app/Http/Requests/StoreAssetRequest.php
app/Models/Asset.php
app/Models/Reservation.php
database/migrations/2021_02_22_075358_alter-table-assets-add-resource-type.php
database/migrations/2021_02_22_093057_alter-table-assets-add-secret-key-client-key.php

- add migration for adding resource type
- add enum for resource type
- update store reservation for check resource type

Update function store reservation

---

app/Http/Controllers/V1/ReservationController.php
app/Policies/ReservationPolicy.php
database/factories/ReservationFactory.php
tests/Feature/ReservationTest.php

- ada salah import class "use App\Reservation", harusnya "use App\Models\Reservation"
- disable approval pas create reservasi
https://trello.com/c/jTUj20dv
https://trello.com/c/rbyAQGiH

fix error delete & update reservasi

---

app/Http/Controllers/V1/ReservationController.php

- remove using `abort_if` on the controller
close #39

#39 remove abort if using Request from Laravel

---

app/Models/Reservation.php

#49 remove unneed format time if using default

---

app/Http/Resources/ReservationResource.php

#57 adding field asset_id`

---

app/Http/Controllers/V1/ReservationListAllController.php
routes/api.php
tests/Feature/ReservationTest.php

This PR refer to task --> https://trello.com/c/z7yp03Dx
Overview:
- Add endpoint baru untuk mendapatkan semua data reservasi (untuk calendar di FE)
- Sudah ditambahkan unit test
Note:
- Tested
cc: kang @rindibudiaramdhan @ayocodingit @setiadijoe @rizkyrmsyah

add endpoint list all reservation for FE calendar

---

app/Http/Requests/StoreAssetRequest.php
tests/Feature/AssetTest.php

ada tambahan untuk validasi type resource pas insert

validate restype

---

resources/views/emails/reservationApproval.blade.php

#64 update field on blade file

---

app/Http/Controllers/V1/ReservationController.php
app/Policies/ReservationPolicy.php

saya remove middleware nya, soalnya kan sekarang admin sama user sama sama bisa create reservasi.
trus di policy nya jg saya tambah

Admin can create

---

app/Events/AfterReservation.php
app/Listeners/CreateZoomMeeting.php
app/Listeners/SendReservationEmail.php
app/Policies/ReservationPolicy.php

User choose zoom room

---

app/Http/Requests/EditAssetRequest.php

update desc value on update asset

---

README.md
docker/docker-entrypoint.sh
docker/php/php.ini

Resolve conflict
cc: kang @rindibudiaramdhan @ayocodingit @setiadijoe @rizkyrmsyah

Fixing resolve conflict prod

---

app/Http/Controllers/V1/CommandCenterReservationController.php

add sorting functoinality in command center reservatoin data retrieving

---

app/Events/CCReservationCreated.php
app/Http/Controllers/V1/CommandCenterReservationApprovalController.php
app/Http/Controllers/V1/CommandCenterReservationController.php
app/Http/Controllers/V1/CommandCenterReservationPublicController.php
app/Http/Requests/CommandCenterReservationApprovalRequest.php
app/Listeners/SendCCReservationEmail.php
app/Mail/CCReservationNotificationMail.php
routes/api.php

Menambahkan validasi untuk fungsi approval reservasi dan menambahkan `approval_date` pada saat melakukan approval reservasi
CC : @jabardigitalservice/jds-backend @yohang88

Add approval validation and approval date

---

resources/views/emails/ccReservationNotification.blade.php

Fix Minor :
CC : @jabardigitalservice/jds-backend @yohang88 @samudra-ajri

Fix email header title

---

app/Http/Controllers/V1/CommandCenterCloseDateController.php

Add sorting functionality for command center disabled dates list.

add sorting command center disabled dates list functionality

---

app/Http/Controllers/V1/CommandCenterReservationController.php

On the command center reservation list, 
- default sorting based on the created time
- admin could search the list by typing the reservation code partly

Modify comcen search feature

---

app/Listeners/SendCCReservationEmail.php

Fix the method name
@jabardigitalservice/jds-backend @iprasetyaa @yohang88

[Hotfix] mail notification listeners

---

app/Http/Requests/CommandCenterReservationCreateRequest.php

CC : @jabardigitalservice/jds-backend @yohang88 @samudra-ajri

Fix validation min value of visitor to 1

---

app/Http/Controllers/V1/CommandCenterReservationController.php
app/Http/Controllers/V1/CommandCenterReservationPublicController.php

CC : @jabardigitalservice/jds-backend @samudra-ajri @ayocodingit

Fix reservation code

---

app/Http/Requests/CommandCenterShiftRequest.php
app/Http/Resources/CCReservationResource.php
app/Models/CommandCenterShift.php
resources/views/emails/ccReservationNotificationAdmin.blade.php
resources/views/emails/ccReservationNotificationPublic.blade.php

CC : @jabardigitalservice/jds-backend @samudra-ajri @ayocodingit

Fix shift sesi label

---

app/Http/Resources/CCReservationResource.php

Fix command center shift full name if data already deleted

---

app/Http/Requests/CommandCenterShiftRequest.php

CC : @jabardigitalservice/jds-backend @samudra-ajri @ayocodingit

Allow cc shift rule unique deleted at  = null

---

app/Mail/CCReservationNotificationMailPublic.php

Modify the conditional parameter using enum.
@sandisunandar99 @iprasetyaa

modify the conditional parameter using enum

---

resources/views/emails/ccReservationNotificationPublic.blade.php

Hotfix mail typo.
@yohang88 @sandisunandar99

Hotfix mail typo

---

resources/views/emails/reservationApproval.blade.php
resources/views/emails/reservationStore.blade.php

Modify mail date format from yyyy-mm-dd hh:mm:ss to dd-mm-yyy hh:mm.

modify mail notification date format

---

app/Http/Controllers/V1/ReservationDailyRecurringController.php

Insert zoom event into daily recurring controller.

add event zoom channel

---

app/Http/Controllers/V1/ReservationDailyRecurringController.php
app/Http/Requests/ReservationRecurringRequest.php
tests/Feature/ReservationDailyRecurringTest.php

Menambahkan logic untuk booking reservasi dengan beberapa aset sekaligus
CC: @jabardigitalservice/jds-backend

Add multiple asset reccuring daily

---

.travis.yml

cc: @jabardigitalservice/jds-backend

add travis code coverage

---

app/Listeners/CreateZoomMeeting.php

Hotfix modify zoom security

---

app/Listeners/CreateZoomMeeting.php

Updated from hotfix https://github.com/jabardigitalservice/reservasi-backend/pull/125.
@rindibudiaramdhan @rachadiannovansyah @ayocodingit

Bugfix zoom security setting

---

app/Listeners/CreateZoomMeeting.php

Menambahkan param auto_recording = cloud pada saat booking zoom
CC: @jabardigitalservice/jds-backend

Add auto recording cloud zoom

---

app/Listeners/CreateZoomMeeting.php

Overview
Hotfix - menambahkan zoom auto recording ke master untuk di production

Hotfix - Add zoom auto recording cloud to main

---

app/Http/Controllers/V1/ReservationListAllController.php

Modify the list that show the records between the current month to the end of year.
@iprasetyaa @ayocodingit  @rachadiannovansyah

Bugfix calendar reservation list

---

app/Exceptions/NoReservationOccurenceException.php
app/Exceptions/NotAvailableAssetException.php
app/Http/Controllers/V1/ReservationDailyRecurringController.php
app/Http/Controllers/V1/ReservationListAllController.php
app/Listeners/CreateZoomMeeting.php

Merubah beberapa kondisi if dengan abort_if
CC: @jabardigitalservice/jds-backend

Clean code

---

app/Listeners/CreateZoomMeeting.php

Memperbaiki typo config settings create zoom meeting

Fix settings create zoom meeting

---

app/Listeners/CreateZoomMeeting.php

Memperbaiki typo config settings create zoom meeting

Hotfix - setting create zoom meeting

---

app/Http/Controllers/V1/ReservationDailyRecurringController.php

- Add condition for ignoring date validation while looping
CC : @jabardigitalservice/jds-backend

Fix validation date on while daily

---

app/Exceptions/NoReservationOccurenceException.php
app/Exceptions/NotAvailableAssetException.php
resources/lang/en/message.php
resources/lang/id/message.php

Modify the message for already reserved asset.

Feature new messages

---

Dockerfile

Issue with Bintray php-alpine resource.
solution: using unofficial resource https://github.com/codecasts/php-alpine/issues/131

modify docker file php-alpine package

---

composer.json
composer.lock

Update version sentry laravel on composer
CC: @jabardigitalservice/jds-backend

Update sentry laravel in composer

---

app/Http/Controllers/V1/ReservationController.php
app/Http/Controllers/V1/ReservationDailyRecurringController.php
app/Http/Requests/CreateReservationRequest.php
app/Traits/ReservationTrait.php

- Modify the single reservation validation to send the error message as FE requesting
- Add traits for asset availability validation

add trait for reusable asset availability validation function

---

composer.json
composer.lock

Reverts jabardigitalservice/reservasi-backend#147

Revert "Update sentry laravel in composer"

---

app/Http/Controllers/V1/ReservationRecurringController.php

Minor clean code recurring reservation feature

---

Dockerfile
composer.json
composer.lock
config/sentry.php

Update laravel-sentry 2.3 to 2.5

Up to Prod - Modify package laravel-sentry

---

app/Http/Controllers/V1/ReservationRecurringController.php

Update from hotfix #159 then create a function to refactor the listCreatedReservation function for codeclimate purpose.

Bugfix and Code Smell - asset already reserved

---

app/Listeners/CreateZoomMeetingRecurring.php

Add tap on update reservation
CC : @jabardigitalservice/jds-backend

Adjust response return from update data

---

Dockerfile

Add laravel optimization - cache

add laravel optimization

---

app/Listeners/CreateZoomMeetingRecurring.php

Removed week iterations function
Change end_times value from week iterations function to total reservations

Bugfix - Remove weekIteration function (unused code)

---

app/Http/Controllers/V1/ReservationRecurringController.php

The monthly recurring need a particular increment, since the initial date should be forced into the date on the first week.

Modify the date increment for monthly recurring

---

Dockerfile

Reverts jabardigitalservice/reservasi-backend#164
@iprasetyaa @ayocodingit

Revert "add laravel optimization"

---

Dockerfile
docker/docker-entrypoint.sh

Move the laravel optimization into entrypoint.
@iprasetyaa @ayocodingit

Modify docker for laravel optimization

---

app/Http/Resources/ReservationResource.php
app/Models/Reservation.php
database/migrations/2021_05_18_045405_alter_reservations_table_add_repeat_type.php

Alter db named repeat_type for new response attributes consists of recurring_id and repeat_type.

add new response attributes

---

app/Http/Requests/ReservationRecurringRequest.php
resources/views/emails/reservationApprovalRecurring.blade.php

Fix carbon get day name on days request

Adjust carbon days for mail template

---

app/Traits/ReservationTrait.php

Previously the week started by Monday, the current state is Sunday.
This modification for zoom api adjustment.

Modify the start day of week for zoom purpose.

---

app/Http/Controllers/V1/ReservationRecurringController.php
app/Traits/ReservationTrait.php

The start day for monthly recurring has to be started by the first day of the month.

Modify initial date monthly recurring

---

app/Http/Controllers/V1/ReservationRecurringController.php
routes/api.php

Add function to delete all records by recurring_id.

add recurring reservation delete functionality

---

app/Traits/ReservationTrait.php

Strictly sperate the initial date of Monthly from Daily and Weekly recurrings.

Modify the recurring initial date.

---

app/Http/Requests/CreateReservationRequest.php
app/Http/Requests/EditReservationRequest.php
app/Http/Requests/ReservationRecurringRequest.php
app/Http/Resources/ReservationResource.php
app/Listeners/CreateZoomMeetingRecurring.php
app/Listeners/SendReservationEmail.php
app/Models/Reservation.php
database/migrations/2021_05_25_063203_alter_reservations_table_add_holder.php
resources/views/emails/reservationApproval.blade.php
resources/views/emails/reservationApprovalRecurring.blade.php

Add holder email for send an email to the owner reservation (https://trello.com/c/Q8YzK9g1)
CC : @jabardigitalservice/jds-backend

Add holder field for send mail to holder

---

app/Listeners/CreateZoomMeetingRecurring.php
resources/views/emails/reservationApproval.blade.php
resources/views/emails/reservationApprovalRecurring.blade.php

Add meeting id & password at email approval reservation recurring and single
CC :  @jabardigitalservice/jds-backend

Add meeting id & password at email approval reservation

---

tests/Feature/ReservationRecurringTest.php

Add the testing for weekly recurring and monthly recurring reservation.

Add weekly and monthly recurring testing
